[project]
name = "class-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.4.0",
    "questionary>=2.1.1",
    "rich>=14.2.0",
    "streamlit>=1.30.0",
]
